[package]
name = "whereismyorigin"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.13.1"
clap = "2.34"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
regex = "1.5"
sled = "0.34.7"
walkdir = "2.5.0"
